// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imagecrop.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the ImageCrop module

	public static java.lang.String getImageCrop_Version()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("ImageCrop.ImageCrop_Version");
	}
}