// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package imagecrop.actions;

import imagecrop.proxies.CropImage;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import javax.imageio.ImageIO;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class SetInitialImageProps extends CustomJavaAction<Boolean>
{
	private IMendixObject UploadedImage;

	public SetInitialImageProps(IContext context, IMendixObject UploadedImage)
	{
		super(context);
		this.UploadedImage = UploadedImage;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		InputStream is;
		try {
			is = Core.getImage(getContext(), this.UploadedImage, false);
			if( is == null )
				return false;
		}
		catch( Exception e ) {
			return false;
		}
		
		BufferedImage img = ImageIO.read(is);
		this.UploadedImage.setValue(getContext(), CropImage.MemberNames.crop_width.toString(), img.getWidth() );
		this.UploadedImage.setValue(getContext(), CropImage.MemberNames.crop_height.toString(), img.getHeight() );
		this.UploadedImage.setValue(getContext(), CropImage.MemberNames.crop_x2.toString(), img.getWidth() );
		this.UploadedImage.setValue(getContext(), CropImage.MemberNames.crop_y2.toString(), img.getHeight() );
		is.close();
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "SetInitialImageProps";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
