// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imagecrop.proxies;

public class Configuration
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ImageCrop.Configuration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		JpegCompressionQuality("JpegCompressionQuality"),
		ThumbnailSize("ThumbnailSize");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Configuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ImageCrop.Configuration"));
	}

	protected Configuration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject)
	{
		if (configurationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ImageCrop.Configuration", configurationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ImageCrop.Configuration");

		this.configurationMendixObject = configurationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Configuration.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static imagecrop.proxies.Configuration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return imagecrop.proxies.Configuration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static imagecrop.proxies.Configuration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new imagecrop.proxies.Configuration(context, mendixObject);
	}

	public static imagecrop.proxies.Configuration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return imagecrop.proxies.Configuration.initialize(context, mendixObject);
	}

	public static java.util.List<imagecrop.proxies.Configuration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<imagecrop.proxies.Configuration> result = new java.util.ArrayList<imagecrop.proxies.Configuration>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ImageCrop.Configuration" + xpathConstraint))
			result.add(imagecrop.proxies.Configuration.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of JpegCompressionQuality
	 */
	public final java.math.BigDecimal getJpegCompressionQuality()
	{
		return getJpegCompressionQuality(getContext());
	}

	/**
	 * @param context
	 * @return value of JpegCompressionQuality
	 */
	public final java.math.BigDecimal getJpegCompressionQuality(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.JpegCompressionQuality.toString());
	}

	/**
	 * Set value of JpegCompressionQuality
	 * @param jpegcompressionquality
	 */
	public final void setJpegCompressionQuality(java.math.BigDecimal jpegcompressionquality)
	{
		setJpegCompressionQuality(getContext(), jpegcompressionquality);
	}

	/**
	 * Set value of JpegCompressionQuality
	 * @param context
	 * @param jpegcompressionquality
	 */
	public final void setJpegCompressionQuality(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal jpegcompressionquality)
	{
		getMendixObject().setValue(context, MemberNames.JpegCompressionQuality.toString(), jpegcompressionquality);
	}

	/**
	 * @return value of ThumbnailSize
	 */
	public final java.lang.Integer getThumbnailSize()
	{
		return getThumbnailSize(getContext());
	}

	/**
	 * @param context
	 * @return value of ThumbnailSize
	 */
	public final java.lang.Integer getThumbnailSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ThumbnailSize.toString());
	}

	/**
	 * Set value of ThumbnailSize
	 * @param thumbnailsize
	 */
	public final void setThumbnailSize(java.lang.Integer thumbnailsize)
	{
		setThumbnailSize(getContext(), thumbnailsize);
	}

	/**
	 * Set value of ThumbnailSize
	 * @param context
	 * @param thumbnailsize
	 */
	public final void setThumbnailSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer thumbnailsize)
	{
		getMendixObject().setValue(context, MemberNames.ThumbnailSize.toString(), thumbnailsize);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configurationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final imagecrop.proxies.Configuration that = (imagecrop.proxies.Configuration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ImageCrop.Configuration";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
