// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package imagecrop.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the ImageCrop module
	public static imagecrop.proxies.Configuration dS_GetConfiguration(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("ImageCrop.DS_GetConfiguration").withParams(params).execute(context);
		return result == null ? null : imagecrop.proxies.Configuration.initialize(context, result);
	}
	public static imagecrop.proxies.Configuration getConfiguration(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("ImageCrop.GetConfiguration").withParams(params).execute(context);
		return result == null ? null : imagecrop.proxies.Configuration.initialize(context, result);
	}
	public static void mB_AlterAspectRatio(IContext context, imagecrop.proxies.CropImage _cropImage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CropImage", _cropImage == null ? null : _cropImage.getMendixObject());
		Core.microflowCall("ImageCrop.MB_AlterAspectRatio").withParams(params).execute(context);
	}
	public static void mB_ApplyAspectRatio(IContext context, imagecrop.proxies.CropImage _cropImage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CropImage", _cropImage == null ? null : _cropImage.getMendixObject());
		Core.microflowCall("ImageCrop.MB_ApplyAspectRatio").withParams(params).execute(context);
	}
	public static void mB_ApplyDraftChanges(IContext context, imagecrop.proxies.CropImage _draftCropImage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DraftCropImage", _draftCropImage == null ? null : _draftCropImage.getMendixObject());
		Core.microflowCall("ImageCrop.MB_ApplyDraftChanges").withParams(params).execute(context);
	}
	public static void mB_ConvertToBW(IContext context, imagecrop.proxies.CropImage _cropImage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CropImage", _cropImage == null ? null : _cropImage.getMendixObject());
		Core.microflowCall("ImageCrop.MB_ConvertToBW").withParams(params).execute(context);
	}
	public static void mB_CreateDraft(IContext context, imagecrop.proxies.CropImage _cropImage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CropImage", _cropImage == null ? null : _cropImage.getMendixObject());
		Core.microflowCall("ImageCrop.MB_CreateDraft").withParams(params).execute(context);
	}
	public static void mB_CropImage(IContext context, imagecrop.proxies.CropImage _cropImage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CropImage", _cropImage == null ? null : _cropImage.getMendixObject());
		Core.microflowCall("ImageCrop.MB_CropImage").withParams(params).execute(context);
	}
	public static void mB_RevertAndCloseDraft(IContext context, imagecrop.proxies.CropImage _draftCropImage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DraftCropImage", _draftCropImage == null ? null : _draftCropImage.getMendixObject());
		Core.microflowCall("ImageCrop.MB_RevertAndCloseDraft").withParams(params).execute(context);
	}
	public static void mB_RevertDraftChanges(IContext context, imagecrop.proxies.CropImage _draftCropImage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DraftCropImage", _draftCropImage == null ? null : _draftCropImage.getMendixObject());
		Core.microflowCall("ImageCrop.MB_RevertDraftChanges").withParams(params).execute(context);
	}
	public static void mB_SaveImage(IContext context, imagecrop.proxies.CropImage _mB_CropImage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MB_CropImage", _mB_CropImage == null ? null : _mB_CropImage.getMendixObject());
		Core.microflowCall("ImageCrop.MB_SaveImage").withParams(params).execute(context);
	}
	public static void mB_ScaleImage(IContext context, imagecrop.proxies.CropImage _cropImage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CropImage", _cropImage == null ? null : _cropImage.getMendixObject());
		Core.microflowCall("ImageCrop.MB_ScaleImage").withParams(params).execute(context);
	}
	public static void saveConfiguration(IContext context, imagecrop.proxies.Configuration _configuration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Configuration", _configuration == null ? null : _configuration.getMendixObject());
		Core.microflowCall("ImageCrop.SaveConfiguration").withParams(params).execute(context);
	}
	public static void sF_CopyImageContents(IContext context, imagecrop.proxies.CropImage _sourceImage, imagecrop.proxies.CropImage _targetImage)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SourceImage", _sourceImage == null ? null : _sourceImage.getMendixObject());
		params.put("TargetImage", _targetImage == null ? null : _targetImage.getMendixObject());
		Core.microflowCall("ImageCrop.SF_CopyImageContents").withParams(params).execute(context);
	}
}